# Generated by Django 5.0.3 on 2024-03-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='text',
            new_name='text_tweet',
        ),
    ]
